import { Button, Metric } from "../../components/ui.jsx";
import { formatInr as money } from "../../lib/formatMoney.js";
import { annualRate, dailyBalance, dailyPaid, dailyProgress, estimatedPenalty, loanPaid, loanStatus, monthlyBalance, monthlyInterestPending, today } from "./model/loanState.js";
import { paymentModeLabel } from "./model/paymentFormat.js";

export function Customer({
  loan,
  logout
}) {
  const monthly = loan.kind === "monthly";
  return <main className="shell" style={{
    maxWidth: 700
  }}><header className="top"><div><div className="brand">FinTrack</div><div className="sub">Customer dashboard</div></div><Button onClick={logout}>Log out</Button></header><h1 className="title">Hello, {loan.customerName}</h1><p className="copy">Your finance ID: {loan.id}</p>{monthly ? <><div className="notice">You have taken {money(loan.principal)} on interest. Pay your monthly interest on time; you may repay the principal whenever you choose.</div><div className="grid metrics"><Metric label="Principal taken" value={money(loan.principal)} color="gold" /><Metric label="Principal remaining" value={money(monthlyBalance(loan))} color="red" /><Metric label="Monthly interest rate" value={`${annualRate(loan, today())}%`} color="blue" /><Metric label="Interest pending" value={money(monthlyInterestPending(loan))} color={monthlyInterestPending(loan) ? "red" : "green"} /><Metric label="Paid so far" value={money(loanPaid(loan))} color="green" /></div><div className="card"><strong>What you need to pay</strong><div className="row spacer"><span className="small">Current monthly interest on balance</span><strong className="gold">{money(Math.round(monthlyBalance(loan) * annualRate(loan, today()) / 100))}</strong></div><div className="row spacer"><span className="small">Estimated missed-payment penalty</span><strong className="red">{money(estimatedPenalty(loan))}</strong></div><p className="notice">Payment can be made via UPI, cash, or bank transfer. Contact your financier to record the payment.</p></div></> : <><div className="notice">You received {money(loan.disbursedAmount)}. Your daily collection plan is {money(loan.collectionAmount)} over 100 days.</div><div className="grid metrics"><Metric label="Amount received" value={money(loan.disbursedAmount)} color="gold" /><Metric label="Total to repay" value={money(loan.collectionAmount)} color="blue" /><Metric label="Daily collection" value={money(loan.dailyCollection)} color="gold" /><Metric label="Paid so far" value={money(dailyPaid(loan))} color="green" /><Metric label="Remaining" value={money(dailyBalance(loan))} color="red" /></div>{loanStatus(loan) === "active" && <div className="card"><strong>Repayment progress</strong><p className="small spacer">{Math.round(dailyPaid(loan) / loan.collectionAmount * 100)}% paid · {dailyProgress(loan).remaining} collection days remaining</p></div>}</>}<div className="card spacer"><strong>Your payment history</strong><div className="table spacer"><table><thead><tr><th>Date</th><th>Amount paid</th><th>Mode</th><th>Reference</th></tr></thead><tbody>{[...loan.transactions].sort((a, b) => b.date.localeCompare(a.date)).map(t => <tr key={t.id}><td>{t.date}</td><td className="green">{money(monthly ? (+t.interestAmount || 0) + (+t.principalAmount || 0) + (+t.penaltyAmount || 0) : t.amount)}</td><td>{paymentModeLabel(t)}</td><td>{t.ref || "—"}</td></tr>)}</tbody></table></div></div></main>;
}
