// Public product copy. Only modules that exist in the workspace are listed.
// `appPath` is where a signed-in owner opens that work. Login is required first.

export const FEATURE_CATEGORIES = [
  { id: "accounts", label: "Accounts", blurb: "Company books for small and medium businesses." },
  { id: "intelligence", label: "AI", blurb: "Ask FinTrack, bill drafts, and suggestions you confirm." },
  { id: "finance", label: "Finance", blurb: "Daily and monthly collections." },
  { id: "chit", label: "Chit Fund", blurb: "Schemes, bidding, and dividends." },
  { id: "portals", label: "Portals", blurb: "Financier sign in opens the owner workspace. Agents, customers, and members have their own login." },
];

export const FEATURES = [
  {
    slug: "dashboard",
    category: "finance",
    name: "Dashboard",
    summary: "One view of today’s collections, chit schemes, and what needs a look.",
    problem: "Daily work is split across notebooks, calls, and separate books.",
    how: ["Open the workspace for your business.", "See today’s collections and scheme activity together.", "Jump into the module that needs you."],
    capabilities: ["Today’s actions", "Daily and monthly customer snapshots", "Chit scheme activity", "Route collection entry when it applies"],
    benefits: ["Start the day from one screen", "See what is still due", "Move into the right module without hunting"],
    related: ["daily-finance", "monthly-finance", "attention-center"],
    appPath: "/dashboard",
    icon: "LayoutDashboard",
  },
  {
    slug: "daily-finance",
    category: "finance",
    name: "Daily Finance",
    summary: "Keep daily collections organized, visible, and ready to record.",
    problem: "A 100-day style account is hard to follow when receipts live in a notebook.",
    how: ["Add a daily customer with the amount and term you agree.", "Record each collection against that account.", "See what was received today and what is still outstanding."],
    capabilities: ["Daily customer accounts", "Today’s collection list", "Balances and paid amounts", "Customer history"],
    benefits: ["Today’s list matches the collections you record", "Outstanding stays visible", "Staff record only the accounts assigned to them"],
    related: ["collections", "digital-receipts", "collection-staff"],
    appPath: "/daily-finance/todays-collections",
    icon: "Sun",
  },
  {
    slug: "monthly-finance",
    category: "finance",
    name: "Monthly Finance",
    summary: "Track monthly interest accounts, dues, and what was collected.",
    problem: "Interest, principal, and penalty get mixed up when they are written in one line.",
    how: ["Open a monthly account for the customer.", "Record interest, principal, and penalty as a collection.", "Review the balance that remains."],
    capabilities: ["Monthly interest accounts", "Due amounts", "Collection history", "Reports for the monthly book"],
    benefits: ["Monthly dues stay separate from daily collections", "Each receipt shows what it covered", "The same customer list can be followed up"],
    related: ["daily-finance", "collections", "customer-statements"],
    appPath: "/monthly-finance/todays-collections",
    icon: "CalendarDays",
  },
  {
    slug: "customers",
    category: "finance",
    name: "Customers",
    summary: "Keep finance customers, their accounts, and their history in the workspace.",
    problem: "The same person is hard to find when daily and monthly accounts live apart.",
    how: ["Create the customer on the finance account.", "Open the account from the customer list.", "Review payments without leaving the workspace."],
    capabilities: ["Active and historical accounts", "Search by name", "Account detail", "Assigned collector where you use staff"],
    benefits: ["One place to find the account", "History stays with the customer", "Owners see the full book; staff see their assignments"],
    related: ["daily-finance", "monthly-finance", "customer-portals"],
    appPath: "/daily-finance/customers",
    icon: "Users",
  },
  {
    slug: "collections",
    category: "finance",
    name: "Collections",
    summary: "See who is due today and record what was received.",
    problem: "A busy collection day hides who has already paid.",
    how: ["Open today’s collections.", "Search by name, phone, or address.", "Record the receipt on that account."],
    capabilities: ["Due today", "Received today", "Search", "Route collections for assigned stops"],
    benefits: ["The day’s progress stays on one list", "A recorded collection updates the account", "Routes help field staff follow their stops"],
    related: ["daily-finance", "collection-staff", "digital-receipts"],
    appPath: "/daily-finance/todays-collections",
    icon: "HandCoins",
  },
  {
    slug: "collection-staff",
    category: "finance",
    name: "Collection Staff",
    summary: "Give collectors an agent ID and PIN, and only the accounts you assign.",
    problem: "Field staff should collect without opening the owner’s full books.",
    how: ["Add a collection agent. FinTrack creates an agent ID and PIN.", "Assign the accounts or route they cover.", "They sign in with Agent login and record those collections."],
    capabilities: ["Agent ID and PIN", "Assigned finance accounts", "Route customers from Accounts", "Owner review of who collected"],
    benefits: ["Staff stay inside their assignment", "The owner still sees the full book", "Route stops can follow the agent you set"],
    related: ["collections", "customers", "whatsapp-reminders"],
    appPath: "/collection-staff",
    icon: "Route",
  },
  {
    slug: "customer-statements",
    category: "finance",
    name: "Customer Statements",
    summary: "Share a statement of the account the customer can review.",
    problem: "Customers ask for a written picture of what they paid and what remains.",
    how: ["Open the customer account.", "Generate the statement from the recorded payments.", "Download it when you are ready to share it."],
    capabilities: ["Account statement", "Payment history", "Download", "Customer portal view of their own balance"],
    benefits: ["The statement follows the recorded account", "You choose when to share it", "The customer portal can show their own history"],
    related: ["customers", "digital-receipts", "customer-portals"],
    appPath: "/daily-finance/users",
    icon: "FileText",
  },
  {
    slug: "digital-receipts",
    category: "finance",
    name: "Digital Receipts",
    summary: "Build a receipt from the collection or voucher you just recorded.",
    problem: "A cash receipt on paper is easy to lose and hard to match later.",
    how: ["Record the collection or voucher.", "Open the receipt from that entry.", "Download or share it when you want the customer to have a copy."],
    capabilities: ["Receipt from a recorded entry", "PDF download", "Business name on the receipt", "Share only when you choose"],
    benefits: ["The receipt matches the entry", "You keep a copy in the workspace", "Sharing stays a separate step"],
    related: ["collections", "whatsapp-reminders", "vouchers"],
    appPath: "/dashboard",
    icon: "Receipt",
  },
  {
    slug: "whatsapp-reminders",
    category: "finance",
    name: "WhatsApp Reminders",
    summary: "Open a WhatsApp message for a reminder. You send it yourself.",
    problem: "Follow-ups stall when the message has to be typed from scratch.",
    how: ["Turn confirmation on in settings if you want it offered.", "FinTrack prepares the message from the entry.", "WhatsApp opens so you can review and send."],
    capabilities: ["Message draft from the entry", "Opens WhatsApp on your device", "Settings for when a confirmation is offered", "No send until you confirm in WhatsApp"],
    benefits: ["The draft follows the recorded amount", "You stay in control of every send", "A number that cannot be used for WhatsApp does not open a chat"],
    related: ["digital-receipts", "collections", "chit-payments"],
    appPath: "/settings/whatsapp",
    icon: "MessageCircle",
  },
  {
    slug: "credit-score",
    category: "finance",
    name: "Credit Score",
    summary: "A FinTrack score from this customer’s payment history in your workspace.",
    problem: "On-time, late, and missed payments are hard to weigh at a glance.",
    how: ["FinTrack reads the payments already on the account.", "It shows a score, a band, and the reasons.", "You use it as context. It does not change the balance or a credit limit."],
    capabilities: ["Score from recorded payments", "On-time, late, missed, and overdue context", "Trend when enough history exists", "Shown on the account, not sent to a bureau"],
    benefits: ["Payment behaviour is easier to see", "The score stays inside your workspace", "Helps you decide whether to give finance the next time", "Nothing is decided for you"],
    related: ["customers", "collections", "anomaly-detection"],
    appPath: "/dashboard",
    icon: "Gauge",
  },
  {
    slug: "auction-chit",
    category: "chit",
    name: "Auction Chit",
    summary: "Run an auction scheme with members, monthly bids, and live bidding.",
    problem: "Auction month, discount, commission, and dividend are easy to miscalculate on paper.",
    how: ["Create an auction scheme and enroll the member count it requires.", "Activate it when the list is complete.", "Record the month from live bidding or a monthly bid."],
    capabilities: ["Scheme value, installment, and commission", "Member tickets", "Monthly bids", "Live bidding for the open month"],
    benefits: ["The month is stored on its own", "Commission and dividend follow the scheme rules", "A member who already won is not offered another bid"],
    related: ["live-bidding", "chit-members", "dividends"],
    appPath: "/chit-fund/schemes",
    icon: "Gavel",
  },
  {
    slug: "fixed-chit",
    category: "chit",
    name: "Fixed Chit",
    summary: "Use a predetermined lift schedule instead of live bidding.",
    problem: "Some schemes promise a lift amount in advance and should not be mixed with an auction.",
    how: ["Choose Fixed Chit or Fixed Predefined Bid when you create the scheme.", "Review the generated schedule.", "Confirm each month from that schedule."],
    capabilities: ["Fixed lift amounts", "Predefined bid schedule with EMI, commission, and net receivable", "Member assignment to a month", "No live bidding on these scheme types"],
    benefits: ["The schedule is visible before the month", "Auction math stays on auction schemes", "You still confirm the month"],
    related: ["auction-chit", "chit-members", "chit-statements"],
    appPath: "/chit-fund/schemes",
    icon: "TableProperties",
  },
  {
    slug: "chit-members",
    category: "chit",
    name: "Chit Members",
    summary: "Enroll members, tickets, and guarantors on the scheme.",
    problem: "A scheme cannot start cleanly until the member list matches the plan.",
    how: ["Add each member with a ticket.", "Enable a private portal when they should see their own scheme.", "Activate only when the active count matches the scheme."],
    capabilities: ["Tickets", "Guarantor details", "Portal access you enable", "Removal only through the controls on that scheme"],
    benefits: ["The list is visible before activation", "Each member has one ticket", "Portal access is a separate step you control"],
    related: ["auction-chit", "member-portals", "chit-payments"],
    appPath: "/chit-fund/schemes",
    icon: "Contact",
  },
  {
    slug: "chit-payments",
    category: "chit",
    name: "Chit Payments",
    summary: "Track the installment due for each member after a month is recorded.",
    problem: "Dividends and net dues are hard to collect from a handwritten sheet.",
    how: ["Record or finalize the month.", "FinTrack creates the installment row for each active member.", "Mark what was paid against that installment."],
    capabilities: ["Installment per member", "Due, paid, and balance", "Month filter", "Outstanding on the member view"],
    benefits: ["Dues follow the recorded month", "Previous months stay as they were", "You record the payment yourself"],
    related: ["dividends", "chit-statements", "auction-chit"],
    appPath: "/chit-fund/schemes",
    icon: "Wallet",
  },
  {
    slug: "live-bidding",
    category: "chit",
    name: "Live Bidding",
    summary: "Open a month, let eligible members bid, and keep the highest bid in view.",
    problem: "A live auction needs one current bid, clear limits, and a record of who led.",
    how: ["Start live bidding for the next open month.", "Members bid from the chit customer login while the auction is open.", "You can pause, resume, and end the month from the owner screen."],
    capabilities: ["Start, pause, and resume", "Bids above commission, within the scheme payout band and 30% cap", "A higher bid replaces the lead", "A repeated submit does not create a second bid"],
    benefits: ["The owner screen shows the current lead", "Ineligible or already-won members cannot bid", "Ending the month is a separate step you confirm"],
    related: ["auction-chit", "member-portals", "dividends"],
    appPath: "/chit-fund/schemes",
    icon: "Radio",
  },
  {
    slug: "dividends",
    category: "chit",
    name: "Dividends",
    summary: "See the discount, commission, and dividend that follow a recorded month.",
    problem: "The amount each member should receive is easy to round differently by hand.",
    how: ["The winning amount is stored with the month.", "Commission is taken from the scheme percent.", "The distributable amount is divided across the member count."],
    capabilities: ["Discount", "Fund manager commission", "Dividend per member", "Month-by-month history"],
    benefits: ["The split follows the scheme you set", "Earlier months are not rewritten", "You can review the figures before you treat them as final"],
    related: ["auction-chit", "chit-payments", "live-bidding"],
    appPath: "/chit-fund/schemes",
    icon: "PieChart",
  },
  {
    slug: "chit-statements",
    category: "chit",
    name: "Chit Statements",
    summary: "Give a member a statement of their scheme, ticket, and payments.",
    problem: "Members ask what they paid and which month they won.",
    how: ["Open the member on the scheme.", "Review winning months and installments.", "Download the customer statement when you want to share it."],
    capabilities: ["Ticket and scheme", "Winning months", "Payment history", "Member portal for their own view"],
    benefits: ["The statement uses the recorded months", "Members can sign in to their own portal", "You still hold the scheme records"],
    related: ["chit-members", "member-portals", "chit-payments"],
    appPath: "/chit-fund/schemes",
    icon: "ScrollText",
  },
  {
    slug: "chit-reports",
    category: "chit",
    name: "Chit Reports",
    summary: "Read scheme, member, and installment activity across the chit book.",
    problem: "A single scheme screen does not show which installments are still open.",
    how: ["Open Chit Fund reports.", "Review schemes, members, and outstanding installments.", "Use the highlights as a prompt to follow up. They do not change the books."],
    capabilities: ["Scheme list", "Outstanding installments", "Upcoming reminders", "Advisory highlights"],
    benefits: ["Open dues are easier to find", "Each scheme stays separate", "Follow-up stays your decision"],
    related: ["auction-chit", "chit-payments", "business-insights"],
    appPath: "/chit-fund/reports",
    icon: "BarChart3",
  },
  {
    slug: "accounts-overview",
    category: "accounts",
    name: "Accounts Overview",
    summary: "Company accounts for small and medium businesses, kept with collections and chit funds.",
    audience: "Small and medium businesses",
    problem: "Sales, stock, supplier bills, and the bank slip into different notebooks as a business grows. A small or medium business needs those in one company book the owner can open and review.",
    how: [
      "Open Accounts and choose the company. A finance business also gets a finance company created with the workspace.",
      "Post receipts, payments, journals, sales, and purchases when debit equals credit.",
      "Follow receivables, payables, stock, GST preparation, and the statements for that company.",
      "Lock a closed period. Sync the cashbook only after integration is on and you choose Sync.",
    ],
    capabilities: ["Company switcher", "Chart of accounts, vouchers, and ledgers", "Receivables, payables, and inventory", "GST preparation, bank reconciliation, and statements"],
    benefits: ["One company book for a small or medium business", "You always see the company you opened", "A voucher, a bank match, and a period lock wait for you"],
    sections: [
      {
        title: "Who Accounts is for",
        text: "Accounts is for a small or medium business: a shop, a trading firm, a service business, or a finance company that also keeps formal books. The owner opens a company, posts the day’s vouchers, and reads the statements. A second company stays separate until you switch to it.",
      },
      {
        title: "The books a growing business needs",
        text: "Start from a chart of accounts. Record receipts, payments, journals, sales, and purchases. See what customers still owe and what you owe suppliers. Keep items and stock with those sales and purchases. Prepare GST from the vouchers you posted, then file the return in your own process. Import a bank statement and accept the matches you agree with. Read the trial balance, profit and loss, balance sheet, and cash flow for the company you have open.",
      },
      {
        title: "Review stays with you",
        text: "A bill photograph, a bank suggestion, and Ask FinTrack can offer a draft. You post the voucher. Debit has to equal credit. A locked month stays locked until you reopen it. The cashbook can stand on its own; its lines enter the finance company only when integration is on and you sync.",
      },
    ],
    related: ["vouchers", "inventory", "gst-preparation", "bank-reconciliation"],
    appPath: "/accounting/overview",
    icon: "Building2",
  },
  {
    slug: "chart-of-accounts",
    category: "accounts",
    name: "Chart of Accounts",
    summary: "Start from a chart of accounts for the company and adjust it as the business needs.",
    problem: "Vouchers need ledgers before they can be posted cleanly.",
    how: ["A new company can be seeded with a chart.", "Add or edit ledgers for that company.", "Use those ledgers when you post."],
    capabilities: ["Seeded chart for a new company", "Ledger groups", "Company-specific accounts", "Edits stay on the company you have open"],
    benefits: ["Posting has a place to land", "Each company keeps its own chart", "You choose the ledger"],
    related: ["ledger", "vouchers", "accounts-overview"],
    appPath: "/accounting/setup",
    icon: "ListTree",
  },
  {
    slug: "ledger",
    category: "accounts",
    name: "Ledger",
    summary: "Read the movements posted to a ledger.",
    problem: "A total is not enough when you need the entries behind it.",
    how: ["Open the ledger section.", "Pick the account.", "Review the posted lines for the period you are looking at."],
    capabilities: ["Ledger balances", "Posted lines", "Drill into the voucher", "Company scope"],
    benefits: ["You can see what made the balance", "Cancelled entries stay identifiable", "The open company is the one you read"],
    related: ["vouchers", "trial-balance", "chart-of-accounts"],
    appPath: "/accounting/ledger",
    icon: "BookOpen",
  },
  {
    slug: "vouchers",
    category: "accounts",
    name: "Vouchers",
    summary: "Post receipts, payments, journals, sales, and purchases when the lines balance.",
    problem: "A voucher that does not balance should not enter the books.",
    how: ["Choose the voucher type.", "Enter the lines.", "Save when debit equals credit. A duplicate purchase can be flagged for you to confirm."],
    capabilities: ["Receipts, payments, journals, sales, and purchases", "Debit must equal credit", "Duplicate purchase warning", "Cancel an accidental posted purchase"],
    benefits: ["Unbalanced vouchers stay out", "You confirm a possible duplicate", "Posted history remains reviewable"],
    related: ["ledger", "bill-scanning", "audit-trail"],
    appPath: "/accounting/transactions",
    icon: "FileSpreadsheet",
  },
  {
    slug: "receivables",
    category: "accounts",
    name: "Receivables",
    summary: "See what customers still owe on the company you have open.",
    problem: "Sales are recorded, then the outstanding is tracked somewhere else.",
    how: ["Post the sale or receipt on the party.", "Open receivables for that company.", "Follow the balance that remains."],
    capabilities: ["Party balances", "Outstanding sales", "Receipts against the party", "Statements"],
    benefits: ["The balance follows posted vouchers", "You collect against the party", "Another company is not mixed in"],
    related: ["payables", "vouchers", "customers"],
    appPath: "/accounting/parties/receivables",
    icon: "ArrowDownLeft",
  },
  {
    slug: "payables",
    category: "accounts",
    name: "Payables",
    summary: "See what you still owe suppliers from posted purchases.",
    problem: "Supplier bills pile up without a clear outstanding list.",
    how: ["Post the purchase.", "Open payables.", "Record the payment when you pay it."],
    capabilities: ["Supplier balances", "Purchase bills", "Payments", "Duplicate bill warning before you rely on a second copy"],
    benefits: ["Outstanding follows the posted bill", "A repeated scan can be flagged", "You decide which bill stands"],
    related: ["receivables", "bill-scanning", "vouchers"],
    appPath: "/accounting/parties/payables",
    icon: "ArrowUpRight",
  },
  {
    slug: "cashbook",
    category: "accounts",
    name: "Cashbook",
    summary: "Record cash and bank movement, then connect it to Accounts only when you sync.",
    problem: "The daily cashbook and the formal books drift apart.",
    how: ["Enter cashbook lines in the cashbook.", "Turn on Accounts integration when you want those lines in the finance company.", "Use Sync to copy linked vouchers. Until then, they stay in the cashbook."],
    capabilities: ["Cash, expense, bank, transfer, and closing", "Opening balances", "Reports", "Sync into the finance company when integration is on"],
    benefits: ["The cashbook can stand on its own", "Sync is a step you take", "Lines land on the finance company, not whichever company happens to be open"],
    related: ["accounts-overview", "bank-reconciliation", "vouchers"],
    appPath: "/cashbook/cashbook",
    icon: "WalletCards",
  },
  {
    slug: "bank-reconciliation",
    category: "accounts",
    name: "Bank Reconciliation",
    summary: "Import a statement and match lines to vouchers you accept.",
    problem: "A bank row and a voucher look related, but they should not be tied without a look.",
    how: ["Import the statement for the bank ledger.", "Review suggested matches.", "Accept the match you agree with. A remembered match can be suggested next time."],
    capabilities: ["Statement import", "Suggested matches", "Accept or leave unmatched", "A prior accepted match can be suggested again"],
    benefits: ["The statement stays visible", "You accept the link", "Unmatched rows remain unmatched until you decide"],
    related: ["cashbook", "bookkeeping-suggestions", "vouchers"],
    appPath: "/accounting/banking",
    icon: "Landmark",
  },
  {
    slug: "trial-balance",
    category: "accounts",
    name: "Trial Balance",
    summary: "Check that the open company’s posted ledgers still balance.",
    problem: "You need a period check before you trust a profit figure.",
    how: ["Open reports and choose Trial Balance.", "Read the ledgers for the company and period.", "Go back to a voucher if a line looks wrong."],
    capabilities: ["Debit and credit totals", "Ledger rows", "Period you select", "Company you have open"],
    benefits: ["Imbalance is visible", "The report follows posted vouchers", "A locked period stays locked until you reopen it"],
    related: ["profit-and-loss", "balance-sheet", "period-locking"],
    appPath: "/accounting/reports/trial",
    icon: "Scale",
  },
  {
    slug: "profit-and-loss",
    category: "accounts",
    name: "Profit & Loss",
    summary: "See income and expense from posted vouchers for the period.",
    problem: "A busy month needs a profit picture that comes from the books, not a separate sheet.",
    how: ["Open the Profit & Loss report.", "Choose the period.", "Review income and expense ledgers."],
    capabilities: ["Income", "Expense", "Period", "Drill-through toward the ledger"],
    benefits: ["The figure follows what was posted", "You can question a line", "It does not invent adjustments"],
    related: ["trial-balance", "balance-sheet", "ledger"],
    appPath: "/accounting/reports/pnl",
    icon: "TrendingUp",
  },
  {
    slug: "balance-sheet",
    category: "accounts",
    name: "Balance Sheet",
    summary: "Read assets, liabilities, and capital from the open company.",
    problem: "The position of the business should come from the same vouchers as the profit report.",
    how: ["Open Balance Sheet.", "Review the groups for the company.", "Trace a balance back to its ledger when you need to."],
    capabilities: ["Assets", "Liabilities", "Equity", "Same posted books as the other statements"],
    benefits: ["One set of books", "Company isolation", "You review before you rely on it"],
    related: ["profit-and-loss", "cash-flow", "trial-balance"],
    appPath: "/accounting/reports/balance",
    icon: "Landmark",
  },
  {
    slug: "cash-flow",
    category: "accounts",
    name: "Cash Flow",
    summary: "See how cash moved in the period from posted activity.",
    problem: "Profit and cash are not the same, and the difference should be visible.",
    how: ["Open the cash flow report.", "Review the movement for the period.", "Compare it with the cashbook when you are reconciling the day."],
    capabilities: ["Period cash movement", "Posted activity", "Company scope"],
    benefits: ["Cash is not hidden inside profit", "You can compare it with the cashbook", "Nothing is forecast into the report"],
    related: ["cashbook", "profit-and-loss", "bank-reconciliation"],
    appPath: "/accounting/reports/cashflow",
    icon: "Waves",
  },
  {
    slug: "inventory",
    category: "accounts",
    name: "Inventory",
    summary: "Keep items, stock movement, and item sales with the company books.",
    problem: "Stock and the sales voucher drift apart when they are tracked in two places.",
    how: ["Add items for the company.", "Use them on sales and purchases.", "Review stock and a physical count when you do one."],
    capabilities: ["Items and categories", "Stock movement", "Item sales", "Physical count"],
    benefits: ["A sale can carry the item", "Stock stays with the company", "You confirm a count rather than trusting a guess"],
    related: ["vouchers", "gst-preparation", "receivables"],
    appPath: "/accounting/inventory",
    icon: "Package",
  },
  {
    slug: "gst-preparation",
    category: "accounts",
    name: "GST Preparation",
    summary: "Prepare GST summaries from posted vouchers. Filing stays outside FinTrack.",
    problem: "Tax totals are slow to gather from individual bills at month end.",
    how: ["Post sales and purchases with the tax you entered.", "Open the GST report or monthly pack.", "Export what you need for your filing workflow."],
    capabilities: ["GST report from posted documents", "Monthly pack", "Export for preparation", "You file with your own process"],
    benefits: ["The summary follows the vouchers", "You can review it before export", "FinTrack does not file the return for you"],
    related: ["vouchers", "inventory", "profit-and-loss"],
    appPath: "/accounting/reports/gst",
    icon: "ReceiptText",
  },
  {
    slug: "audit-trail",
    category: "accounts",
    name: "Audit Trail",
    summary: "See who changed accounting setup and vouchers worth reviewing.",
    problem: "A later question needs to know what changed, not only the current balance.",
    how: ["Open the audit trail in Accounts setup.", "Review the recorded events for the company.", "Use it to trace a change. It does not rewrite the voucher."],
    capabilities: ["Recorded accounting events", "Company scope", "Review after the fact"],
    benefits: ["Changes are easier to trace", "The books stay the source of the balance", "Review is separate from posting"],
    related: ["vouchers", "period-locking", "ledger"],
    appPath: "/accounting/setup",
    icon: "ScrollText",
  },
  {
    slug: "period-locking",
    category: "accounts",
    name: "Period Locking",
    summary: "Lock a date range so later edits do not silently change a closed period.",
    problem: "A closed month should not move because someone posts into it later.",
    how: ["Choose the dates to lock.", "Save the lock.", "Reopen it yourself when a correction is actually needed."],
    capabilities: ["Lock a date range", "Blocked posting into a locked period", "Reopen when you decide"],
    benefits: ["Closed dates stay closed", "A correction is explicit", "The lock is yours to lift"],
    related: ["audit-trail", "vouchers", "trial-balance"],
    appPath: "/accounting/setup",
    icon: "Lock",
  },
  {
    slug: "business-insights",
    category: "intelligence",
    name: "Business Insights",
    summary: "Short highlights drawn from the records already in the module you are viewing.",
    problem: "The important follow-up is buried under a long list.",
    how: ["Open Dashboard, Chit Fund, or Accounts.", "Read the insight card for that module.", "Treat it as a prompt. It does not post, send, or change a balance."],
    capabilities: ["Module insights", "Based on records in the workspace", "Advisory only"],
    benefits: ["A long list gets a shorter reading", "You still open the underlying record", "Nothing is booked from the card"],
    related: ["attention-center", "ask-the-books", "anomaly-detection"],
    appPath: "/dashboard",
    icon: "Sparkles",
  },
  {
    slug: "ask-the-books",
    category: "intelligence",
    name: "Ask the Books",
    summary: "Ask about receivables, profit, GST, collections, or the cashbook. The answer stays in this workspace.",
    problem: "Looking up a balance or a due list should not mean opening every screen.",
    how: ["Open Ask FinTrack from the workspace.", "Ask about the company and records you can already see.", "Read the answer and open the screen if you want to act."],
    capabilities: ["Receivables, profit, expenses, and GST", "Who has not paid, and how this month compares", "A simple outlook from recent records", "Nothing is posted by asking"],
    benefits: ["Answers stay inside your data", "A draft is not a sent message", "You confirm anything that would change the books"],
    sections: [
      { title: "Questions it can take", text: "On Accounts you can ask why profit moved, which expenses rose, which receivables are due, or to open the GST report. On collections you can ask who has not paid today and how this month compares with the last. On the cashbook you can ask why it differs from Accounts." },
      { title: "An outlook you can ask for", text: "A forward-looking question can return a simple outlook from recent records. That answer lives in Ask FinTrack. It is not written into the books, and it does not set a target." },
    ],
    related: ["business-insights", "forecasting", "collection-priorities"],
    appPath: "/dashboard",
    icon: "MessageCircle",
  },
  {
    slug: "attention-center",
    category: "intelligence",
    name: "Attention Center",
    summary: "A list of collections, dues, and items that look like they need a person.",
    problem: "The next follow-up is not always the first row on the screen.",
    how: ["FinTrack gathers pending daily collections, monthly dues, and similar items.", "Each item points at the module where you can act.", "Opening it does not record a payment."],
    capabilities: ["Pending daily collections", "Monthly dues", "Links into the module", "Advisory list"],
    benefits: ["The next look is named", "You still record the collection", "The list does not auto-collect"],
    related: ["collection-priorities", "collections", "business-insights"],
    appPath: "/dashboard",
    icon: "Bell",
  },
  {
    slug: "collection-priorities",
    category: "intelligence",
    name: "Collection Priorities",
    summary: "Highlights who is still due so the day’s follow-up is easier to start.",
    problem: "A full customer list does not say who has not paid today.",
    how: ["Today’s unpaid daily accounts are named.", "Monthly dues can be grouped so the amount is visible.", "You open the account and record the collection if it was received."],
    capabilities: ["Unpaid today", "Monthly due context", "Link to the finance list"],
    benefits: ["The follow-up starts from a name", "The Daily Finance total stays the source of what was received", "Priority is a suggestion"],
    related: ["collections", "attention-center", "anomaly-detection"],
    appPath: "/daily-finance/todays-collections",
    icon: "ListChecks",
  },
  {
    slug: "anomaly-detection",
    category: "intelligence",
    name: "Anomaly Detection",
    summary: "Flags a collection day that looks unlike recent daily receipts.",
    problem: "A unusual day is easy to miss when the total still looks plausible.",
    how: ["FinTrack compares recent Daily Finance receipt days.", "A day that is far above the recent pattern can be named.", "The notice does not reverse or block the receipt."],
    capabilities: ["Daily collection pattern", "Names the day and the amount", "Does not treat the day as fraud", "Does not change the books"],
    benefits: ["An unusual day is visible", "You decide what it means", "The Daily Finance total remains the record"],
    related: ["collections", "business-insights", "credit-score"],
    appPath: "/dashboard",
    icon: "ShieldAlert",
  },
  {
    slug: "bill-scanning",
    category: "intelligence",
    name: "Bill Scanning",
    summary: "Photograph a supplier bill and review a draft before anything is posted.",
    problem: "Typing a purchase from a paper bill is slow, and a second photo of the same bill is easy to save twice.",
    how: ["Take or upload a photo.", "FinTrack fills a draft and can match a supplier.", "You review it. A possible duplicate must be confirmed. Save is what posts."],
    capabilities: ["Photo to draft", "Supplier match by GSTIN or name", "Suggested expense ledger", "Duplicate warning before use"],
    benefits: ["The draft is not a voucher yet", "You can see a possible duplicate", "Posting happens when you save"],
    related: ["vouchers", "payables", "bookkeeping-suggestions"],
    appPath: "/accounting/transactions",
    icon: "ScanLine",
  },
  {
    slug: "bookkeeping-suggestions",
    category: "intelligence",
    name: "Bookkeeping Suggestions",
    summary: "Suggests an expense ledger and a bank line for you to accept.",
    problem: "The same kind of bill or bank row gets coded differently each time.",
    how: ["A scanned bill can suggest an expense ledger.", "A bank line can suggest the match you accepted last time.", "Nothing is posted until you save or accept it."],
    capabilities: ["Expense suggestion on a bill draft", "Bank line suggestion from a prior accepted match", "You confirm"],
    benefits: ["Repeat coding is faster to review", "The suggestion can be wrong, so it waits", "The books change only when you accept"],
    related: ["bill-scanning", "bank-reconciliation", "vouchers"],
    appPath: "/accounting/banking",
    icon: "Lightbulb",
  },
  {
    slug: "forecasting",
    category: "intelligence",
    name: "Forecasting",
    summary: "Ask FinTrack can sketch a simple outlook from recent records.",
    problem: "A rough sense of what recent collections imply should not require a separate spreadsheet.",
    how: ["Ask FinTrack a forward-looking question.", "It answers from recent records in this workspace.", "Treat the answer as a sketch. It is not posted into the books."],
    capabilities: ["Outlook from recent records", "Asked inside Ask FinTrack", "No automatic budget or target"],
    benefits: ["You can ask without leaving the workspace", "The sketch stays advisory", "You do not book a forecast by asking"],
    related: ["ask-the-books", "collections", "cash-flow"],
    appPath: "/dashboard",
    icon: "LineChart",
    advisory: true,
  },
  {
    slug: "agent-portal",
    category: "portals",
    name: "Agent Portal",
    summary: "A collection agent signs in with an agent ID and PIN to the accounts and routes you assign.",
    problem: "Field staff should record collections without opening the owner’s books, chit schemes, or company accounts.",
    how: ["Add the agent under Collection Staff. FinTrack creates an agent ID and PIN.", "Share them privately, then assign the finance accounts or route they cover.", "They use Agent login. The owner books stay with you."],
    capabilities: ["Agent ID starting with AG- and a 6-digit PIN", "Assigned finance accounts", "Route stops when the agent is set on a route", "No chit book, cashbook, or company accounts"],
    benefits: ["Collectors work their own list", "A recorded collection stays on that account", "You still review the full book"],
    related: ["collection-staff", "collections", "customer-portals"],
    appPath: "/login",
    icon: "Users",
  },
  {
    slug: "customer-portals",
    category: "portals",
    name: "Customer Portal",
    summary: "A finance customer signs in with a portal ID and PIN to see their own account.",
    problem: "Customers want their balance without access to the rest of the business.",
    how: ["Enable the customer portal on the account.", "Share the portal ID and PIN privately.", "They sign in as a customer and see their loan and history."],
    capabilities: ["Portal ID and PIN", "Own balance and history", "No access to other customers", "Statement download on their view"],
    benefits: ["The customer sees their account", "The owner workspace stays separate", "You choose when the portal is on"],
    related: ["customers", "customer-statements", "digital-receipts"],
    appPath: "/login",
    icon: "UserRound",
  },
  {
    slug: "member-portals",
    category: "portals",
    name: "Member Portal",
    summary: "A chit member signs in to see their scheme and, when bidding is open, post a bid.",
    problem: "Members should bid and read their own ticket without seeing the whole scheme book.",
    how: ["Enable the chit portal and set a PIN.", "Share the portal ID privately.", "The member signs in as a chit customer."],
    capabilities: ["Own ticket and scheme", "Payment history", "Live bid when the auction is open and they are eligible", "No view of other members’ private records"],
    benefits: ["Bidding comes from the member", "The owner still starts and ends the auction", "Portal access is yours to reset"],
    related: ["live-bidding", "chit-members", "chit-statements"],
    appPath: "/login",
    icon: "Ticket",
  },
];

export function featuresInCategory(categoryId) {
  return FEATURES.filter(feature => feature.category === categoryId);
}

export function featureBySlug(slug) {
  return FEATURES.find(feature => feature.slug === slug) || null;
}

export function relatedFeatures(feature) {
  if (!feature) return [];
  return feature.related.map(slug => featureBySlug(slug)).filter(Boolean);
}

export const PILLARS = [
  {
    slug: "daily-finance",
    eyebrow: "Collections",
    title: "Finance and collection workflow",
    text: "Daily and monthly accounts, today’s list, receipts, and the staff who collect — with the customer’s own portal when you enable it.",
  },
  {
    slug: "accounts-overview",
    eyebrow: "Books",
    title: "Accounts for small and medium businesses",
    text: "Shops, trading firms, service businesses, and finance companies keep a company book here: balanced vouchers, stock, GST preparation, bank matches, and statements. You open the company, and you confirm the voucher.",
  },
  {
    slug: "live-bidding",
    eyebrow: "Chit Fund",
    title: "Chit Fund workflow",
    text: "Schemes, members, live bidding, dividends, and statements. The owner starts the month. Members bid from their portal. You confirm the close.",
  },
];

export const SOLUTIONS = [
  {
    title: "Finance businesses",
    text: "Keep customer accounts, daily collections, monthly repayments, and collection staff in one login.",
    features: ["daily-finance", "monthly-finance", "collection-staff"],
  },
  {
    title: "Chit fund operators",
    text: "Run schemes, members, live bidding, installments, dividends, and statements.",
    features: ["auction-chit", "live-bidding", "chit-payments"],
  },
  {
    title: "Shops and traders",
    text: "Post sales and purchases, keep stock, and read receivables and payables for the company you have open.",
    features: ["vouchers", "inventory", "receivables"],
  },
  {
    title: "Service businesses",
    text: "Record invoices, expenses, and payments, then read profit and cash for the period.",
    features: ["vouchers", "profit-and-loss", "cash-flow"],
  },
  {
    title: "Small and medium businesses",
    text: "Bring the chart of accounts, GST preparation, banking, inventory, receivables, and payables into one company book.",
    features: ["accounts-overview", "gst-preparation", "bank-reconciliation"],
  },
];

export const SECURITY_POINTS = [
  {
    title: "Sign-in for each role",
    text: "Financier sign in uses email and opens the owner workspace. A collection agent uses an agent ID and PIN. A finance customer and a chit member use a portal ID and PIN. A staff login does not open the owner books.",
  },
  {
    title: "Workspace isolation",
    text: "Records belong to the business workspace. Another organisation’s customers, schemes, and vouchers are not part of this login.",
  },
  {
    title: "Company separation in Accounts",
    text: "Accounts can hold more than one company. Reports and vouchers follow the company you have open. The finance company is not silently replaced by another company.",
  },
  {
    title: "Accounting permissions",
    text: "Chit Fund, Cashbook, and Accounts are owner modules. Collection agents work the accounts and routes assigned to them.",
  },
  {
    title: "Audit trail",
    text: "Accounting keeps a trail of changes you can review. The trail does not rewrite a voucher by itself.",
  },
  {
    title: "Period locking",
    text: "Lock a date range when a period should stay still. Reopen it when you decide a correction is needed.",
  },
  {
    title: "Balanced vouchers",
    text: "A voucher is saved when debit equals credit. That check is the posting rule, not a suggestion.",
  },
  {
    title: "Integration stays off until you sync",
    text: "Cashbook lines are copied into the finance company only after Accounts integration is on and you sync. Turning the switch on does not post by itself.",
  },
  {
    title: "Suggestions wait for you",
    text: "Insights, bill drafts, bank matches, and Ask FinTrack answers are advisory. Payments, bids, messages, and vouchers change when a person confirms them.",
  },
];
