/** Final shared style layer for FinTrack's light-first staging design system. */
export const fintrackLightTheme = `
:root{
  color-scheme:light!important;
  --ft-bg:#f6f8fb;--ft-surface:#fff;--ft-surface-subtle:#f8fafc;--ft-surface-muted:#f1f5f9;
  --ft-text:#172033;--ft-text-2:#475467;--ft-muted:#667085;--ft-border:#dbe3ee;--ft-border-strong:#c8d3e1;
  --ft-primary:#315fba;--ft-primary-hover:#274e9b;--ft-primary-soft:#eaf1ff;
  --ft-success:#168a63;--ft-success-soft:#e9f8f1;--ft-warning:#b7791f;--ft-warning-soft:#fff6df;
  --ft-danger:#d14355;--ft-danger-soft:#fff0f2;--ft-info:#356fc4;--ft-info-soft:#edf4ff;
  --ft-radius-sm:8px;--ft-radius:12px;--ft-radius-lg:16px;
  --ft-shadow-sm:0 1px 2px rgba(16,24,40,.04);--ft-shadow:0 8px 24px rgba(16,24,40,.07);--ft-shadow-lg:0 24px 64px rgba(16,24,40,.16);
  font:16px/1.45 DM Sans,system-ui,sans-serif!important;background:var(--ft-bg)!important;color:var(--ft-text)!important;
}
html,body,#root{background:var(--ft-bg)!important;color:var(--ft-text)!important}
body{min-width:320px}.app{background:var(--ft-bg)!important;color:var(--ft-text)!important}
::selection{background:#cfe0ff;color:#173567}

/* Type */
.title,.shell .title,.shell .title *,.accounts-dashboard h1,.accounts-dashboard h2,.accounts-dashboard h3,.accounts-dashboard h4,.accounts-dashboard .accounts-panel-title{color:var(--ft-text)!important}
.brand{color:var(--ft-primary)!important}.sub,.small,.copy{color:var(--ft-muted)!important}
.gold{color:var(--ft-warning)!important}.green{color:var(--ft-success)!important}.red{color:var(--ft-danger)!important}.blue{color:var(--ft-info)!important}

/* Shared actions */
.btn{min-height:40px!important;padding:8px 13px!important;border:1px solid var(--ft-border-strong)!important;border-radius:10px!important;background:var(--ft-surface)!important;color:var(--ft-text-2)!important;box-shadow:var(--ft-shadow-sm)!important;font-weight:650!important;transition:background .15s,border-color .15s,color .15s,box-shadow .15s,transform .15s!important}
.btn:hover{background:var(--ft-surface-subtle)!important;border-color:#9aacc3!important;box-shadow:0 3px 10px rgba(16,24,40,.08)!important;transform:translateY(-1px)}
.btn:focus-visible,.link-button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid rgba(49,95,186,.22)!important;outline-offset:2px!important}
.btn.primary{background:var(--ft-primary)!important;border-color:var(--ft-primary)!important;color:#fff!important;box-shadow:0 5px 14px rgba(49,95,186,.18)!important}
.btn.primary:hover{background:var(--ft-primary-hover)!important;border-color:var(--ft-primary-hover)!important}
.btn.danger{background:var(--ft-surface)!important;border-color:#efb7c0!important;color:var(--ft-danger)!important}.btn.danger:hover{background:var(--ft-danger-soft)!important}
.btn:disabled{opacity:.48!important;box-shadow:none!important;transform:none!important}.tab{background:transparent!important;border-color:transparent!important;color:var(--ft-muted)!important;box-shadow:none!important}.tab.active{background:var(--ft-primary-soft)!important;border-color:#bdd0f4!important;color:var(--ft-primary)!important}
.link-button,.phone-link{color:var(--ft-primary)!important}

/* Forms */
.field label,.accounts-filter-field .small{color:var(--ft-text-2)!important}.field input,.field select,.field textarea,input.accounts-search,.accounts-filter-field input,.accounts-filter-field select,.acc-new-entry,.customer-search input,.collection-search input{min-height:42px!important;background:var(--ft-surface)!important;color:var(--ft-text)!important;border:1px solid var(--ft-border-strong)!important;border-radius:10px!important;box-shadow:inset 0 1px 1px rgba(16,24,40,.02)!important}
input::placeholder,textarea::placeholder{color:#98a2b3!important}input:disabled,select:disabled,textarea:disabled{background:var(--ft-surface-muted)!important;color:#7b8797!important}

/* Surfaces */
.card{background:var(--ft-surface)!important;border:1px solid var(--ft-border)!important;border-radius:var(--ft-radius-lg)!important;box-shadow:var(--ft-shadow-sm)!important;color:var(--ft-text)!important}.card:hover{border-color:var(--ft-border-strong)!important}
.metrics{gap:12px!important}.metrics .card,.metrics button.card.metric-link{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important;padding:16px 17px!important}.metrics .card:before{width:3px!important;background:var(--ft-primary)!important}.metric-label{color:var(--ft-muted)!important}.metric-value{color:var(--ft-text)!important}.metric-value.gold{color:var(--ft-warning)!important}.metric-value.green{color:var(--ft-success)!important}.metric-value.red{color:var(--ft-danger)!important}.metric-value.blue{color:var(--ft-info)!important}
.notice{background:var(--ft-warning-soft)!important;color:#76500f!important;border:1px solid #eed59d!important;border-left:3px solid var(--ft-warning)!important;border-radius:10px!important}.notice.red,.notice.error{background:var(--ft-danger-soft)!important;color:#9c2f40!important;border-color:#f0bec6!important}.accounts-notice-ok{background:var(--ft-success-soft)!important;color:#116b4d!important;border-color:#a9dec9!important}

/* Tables */
.table{background:var(--ft-surface)!important;border:1px solid var(--ft-border)!important;border-radius:12px!important}.table table{background:transparent!important}.table th{background:var(--ft-surface-subtle)!important;color:var(--ft-muted)!important;border-color:var(--ft-border)!important}.table td{color:var(--ft-text-2)!important;border-color:#e7ecf3!important}.table tbody tr:hover{background:#f8fbff!important}.table tbody tr:last-child td{border-bottom-color:transparent!important}

/* Status */
.badge,.acc-status-pill,.accounts-industry-badge{border:1px solid transparent!important}.badge.active,.badge.completed,.badge.paid,.acc-status-pill.active,.acc-chip.ok{background:var(--ft-success-soft)!important;color:var(--ft-success)!important;border-color:#bce5d6!important}.badge.overdue,.badge.bankrupt,.badge.cancelled,.acc-status-pill.inactive{background:var(--ft-danger-soft)!important;color:var(--ft-danger)!important;border-color:#f2c4cb!important}.badge.closed,.badge.pending,.badge.draft{background:var(--ft-warning-soft)!important;color:#946215!important;border-color:#efdba9!important}

/* Modals */
.modal-bg{background:rgba(15,23,42,.38)!important;backdrop-filter:blur(5px)!important}.modal,.acc-modal{background:var(--ft-surface)!important;color:var(--ft-text)!important;border:1px solid var(--ft-border)!important;border-radius:18px!important;box-shadow:var(--ft-shadow-lg)!important}

/* Finance shell/navigation */
.shell{color:var(--ft-text)!important}.financier-nav{background:rgba(255,255,255,.96)!important;border:1px solid var(--ft-border)!important;box-shadow:var(--ft-shadow)!important;backdrop-filter:blur(18px)!important}.financier-nav .nav-title{color:var(--ft-primary)!important}.financier-nav .nav-footer{color:var(--ft-muted)!important;border-color:var(--ft-border)!important}.financier-nav button{color:var(--ft-text-2)!important;background:transparent!important}.financier-nav button.tab.active{background:var(--ft-primary-soft)!important;border-color:#c4d5f3!important;color:var(--ft-primary)!important}.nav-glyph{background:#eef3fa!important;color:#526b8f!important}.financier-nav .tab.active .nav-glyph{background:#dbe8ff!important;color:var(--ft-primary)!important}.financier-nav-more{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow)!important}
.dashboard-home .toolbar{background:var(--ft-surface)!important;border:1px solid var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important}.dashboard-home .toolbar .title{color:var(--ft-text)!important}.dashboard-quick-action{background:var(--ft-surface)!important;color:var(--ft-text)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important}.dashboard-quick-action:hover{background:#f8fbff!important;border-color:#abc1df!important}.dashboard-quick-action-icon{background:var(--ft-primary-soft)!important;color:var(--ft-primary)!important}.dashboard-section-summary{background:var(--ft-surface-subtle)!important;color:var(--ft-text-2)!important;border-color:var(--ft-border)!important}
.dashboard-finance-section,.chit-board,.dashboard-chit-panel{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important}.dashboard-finance-heading strong,.dashboard-customers-toggle,.chit-board-title strong{color:var(--ft-text)!important}.dashboard-customers-toggle,.dashboard-finance-table{border-color:var(--ft-border)!important}.dashboard-reorder-hint{color:var(--ft-muted)!important}.dashboard-finance-icon,.chit-board-icon,.dashboard-chit-icon{background:var(--ft-primary-soft)!important;border-color:#c8d9f5!important;color:var(--ft-primary)!important}
.dashboard-finance-table tr,.upcoming-payments-table tr{background:var(--ft-surface)!important;border-color:var(--ft-border)!important}.customer-actions{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow)!important}.chit-scheme-card{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important;color:var(--ft-text)!important}.chit-scheme-card:hover{border-color:#9db4d4!important;box-shadow:var(--ft-shadow)!important}.chit-scheme-name,.chit-scheme-current strong{color:var(--ft-text)!important}.chit-scheme-value-label,.chit-scheme-current span{color:var(--ft-muted)!important}
.collection-summary>div,.collection-card{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important}.collection-section h2,.collection-info strong{color:var(--ft-text)!important}.collection-summary span,.collection-info span,.collection-amount small{color:var(--ft-muted)!important}.collection-avatar{background:var(--ft-info-soft)!important;color:var(--ft-info)!important}

/* Standalone Finance Cashbook (outside the Accounts dashboard scope) */
.accounts-module .accounts-balance-item,.accounts-module .accounts-closing-stats>div{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important;color:var(--ft-text)!important}.accounts-module .accounts-balance-move{background:var(--ft-surface-subtle)!important}.accounts-module .accounts-balance-item span,.accounts-module .accounts-closing-stats span,.accounts-module .accounts-balance-hint{color:var(--ft-muted)!important}.accounts-module .accounts-balance-item strong{color:var(--ft-text)!important}.accounts-module .accounts-balance-item strong.gold{color:var(--ft-warning)!important}.accounts-module .accounts-balance-item strong.green{color:var(--ft-success)!important}.accounts-module .accounts-balance-item strong.red{color:var(--ft-danger)!important}

/* Chit surfaces */
.chit-dashboard{background:var(--ft-bg)!important;color:var(--ft-text)!important}.dashboard-chit-card{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important}.dashboard-chit-card:before{background:var(--ft-primary)!important}.dashboard-chit-name,.dashboard-chit-stats strong{color:var(--ft-text)!important}.dashboard-chit-value{color:var(--ft-warning)!important}.dashboard-chit-stats{border-color:var(--ft-border)!important}.dashboard-chit-stats span{color:var(--ft-muted)!important}.dashboard-chit-type{background:var(--ft-info-soft)!important;color:var(--ft-info)!important}
.chit-fund-page,.chit-fund-page .shell{background:transparent!important;color:var(--ft-text)!important}.chit-fund-page .card,.chit-fund-page .chit-board{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;color:var(--ft-text)!important}

/* Accounts design system */
.accounts-dashboard{--acc-bg:var(--ft-bg)!important;--acc-surface:var(--ft-surface)!important;--acc-card:var(--ft-surface)!important;--acc-card-elevated:var(--ft-surface-subtle)!important;--acc-line:var(--ft-border)!important;--acc-line-strong:var(--ft-border-strong)!important;--acc-text:var(--ft-text)!important;--acc-muted:var(--ft-muted)!important;--acc-gold:var(--ft-warning)!important;--acc-gold-ink:#fff!important;--acc-green:var(--ft-success)!important;--acc-red:var(--ft-danger)!important;--acc-blue:var(--ft-info)!important;--acc-shadow:var(--ft-shadow)!important;--acc-shadow-soft:var(--ft-shadow-sm)!important;background:var(--ft-bg)!important;color:var(--ft-text)!important}
.accounts-dashboard .acc-sidebar{background:var(--ft-surface)!important;border-color:var(--ft-border)!important}.accounts-dashboard .acc-sidebar-brand strong{color:var(--ft-text)!important}.accounts-dashboard .acc-nav-item,.accounts-dashboard .acc-nav-sub,.accounts-dashboard .acc-nav-toggle{color:var(--ft-text-2)!important}.accounts-dashboard .acc-nav-item:hover,.accounts-dashboard .acc-nav-item.active,.accounts-dashboard .acc-nav-sub.active{background:var(--ft-primary-soft)!important;color:var(--ft-primary)!important}.accounts-dashboard .acc-nav-glyph{background:#eef3fa!important;color:#526b8f!important}.accounts-dashboard .acc-main,.accounts-dashboard .acc-shell{background:transparent!important}.accounts-dashboard .acc-page-head,.accounts-dashboard .acc-company-bar,.accounts-dashboard .acc-ov-context-bar,.accounts-dashboard .accounts-filter-card{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important}.accounts-dashboard .card,.accounts-dashboard .acc-setup-section,.accounts-dashboard .acc-ov-chart,.accounts-dashboard .attention-center,.accounts-dashboard .acc-intelligence-card{background:var(--ft-surface)!important;border-color:var(--ft-border)!important;color:var(--ft-text)!important;box-shadow:var(--ft-shadow-sm)!important}.accounts-dashboard .accounts-industry-card{background:linear-gradient(135deg,#f0f6ff,#fff8e9)!important;border-color:#d9e5f4!important}.accounts-dashboard .accounts-industry-head h2,.accounts-dashboard .manufacturing-flow-card,.accounts-dashboard .accounts-ledger-name,.accounts-dashboard .accounts-ledger-balance{color:var(--ft-text)!important}.accounts-dashboard .accounts-template-features span{background:#fff7df!important;border-color:#ead69f!important;color:#805811!important}.accounts-dashboard .accounts-industry-badge{background:#fff4d7!important;border-color:#e9d39b!important;color:#926313!important}
.accounts-dashboard .acc-nav-flyout,.accounts-dashboard .acc-user-menu,.accounts-dashboard .acc-gst-setup-hint,.accounts-dashboard .acc-gst-preview,.accounts-dashboard .acc-form-section{background:var(--ft-surface)!important;border-color:var(--ft-border)!important}.accounts-dashboard .acc-ov-context{background:linear-gradient(135deg,#f7faff 0%,#fff 58%,#fff9ed 100%)!important;border-color:var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important}.accounts-dashboard .acc-ov-aging-bar{background:#e8edf4!important}.accounts-dashboard .acc-ov-more-menu button:hover,.accounts-dashboard .acc-ov-more-menu button:focus-visible,.accounts-dashboard .acc-table-wrap tbody tr:hover{background:#f3f7fc!important}.accounts-dashboard .acc-switch{background:#c9d3e1!important}.accounts-dashboard .acc-bottom-item{color:var(--ft-text-2)!important}.accounts-dashboard .acc-bottom-item.active{background:var(--ft-primary-soft)!important;color:var(--ft-primary)!important}.accounts-dashboard .acc-toast.error{background:var(--ft-danger-soft)!important;border-color:#efbec7!important;color:#9c2f40!important}.accounts-dashboard .acc-toast.ok{background:var(--ft-success-soft)!important;border-color:#b8e2d3!important;color:#116b4d!important}
.accounts-dashboard input,.accounts-dashboard select,.accounts-dashboard textarea,.accounts-dashboard .acc-new-entry{background:var(--ft-surface)!important;color:var(--ft-text)!important;border-color:var(--ft-border-strong)!important}.accounts-dashboard .btn{background:var(--ft-surface)!important;color:var(--ft-text-2)!important;border-color:var(--ft-border-strong)!important}.accounts-dashboard .btn.primary{background:var(--ft-primary)!important;border-color:var(--ft-primary)!important;color:#fff!important}.accounts-dashboard .acc-metric-card,.accounts-dashboard .accounts-balance-item,.accounts-dashboard .accounts-closing-stats>div,.accounts-dashboard .acc-invoice-kpi{background:var(--ft-surface)!important;border-color:var(--ft-border)!important}.accounts-dashboard .accounts-business-pulse{background:linear-gradient(145deg,#fff,#f7faff)!important}.accounts-dashboard .accounts-business-action{background:var(--ft-surface)!important;color:var(--ft-text-2)!important}.accounts-dashboard .accounts-business-alert{background:var(--ft-warning-soft)!important}.accounts-dashboard .attention-center-item{background:var(--ft-surface-subtle)!important;border-color:var(--ft-border)!important}.accounts-dashboard .acc-ov-pie-bg{fill:#eef2f7!important}.accounts-dashboard .acc-ov-pie-hole{fill:#fff!important}.accounts-dashboard .acc-skeleton{background:linear-gradient(90deg,#edf1f6 0%,#f8fafc 50%,#edf1f6 100%)!important}
.accounts-dashboard .table,.accounts-dashboard table{background:var(--ft-surface)!important}.accounts-dashboard th{background:var(--ft-surface-subtle)!important;color:var(--ft-muted)!important;border-color:var(--ft-border)!important}.accounts-dashboard td{color:var(--ft-text-2)!important;border-color:#e7ecf3!important}.accounts-dashboard tbody tr:hover{background:#f8fbff!important}

/* AI language */
.module-insights-card,.acc-intelligence-card,.attention-center{background:var(--ft-surface)!important;border:1px solid var(--ft-border)!important;box-shadow:var(--ft-shadow-sm)!important}.module-insights-card:before,.acc-intelligence-card:before{background:var(--ft-primary)!important}.module-insights-card h3,.acc-intelligence-card h3,.attention-center-summary{color:var(--ft-text)!important}
.module-intel,.dashboard-finance-section .module-intel,.module-intel-metrics div,.attention-center-item{background:var(--ft-surface-subtle)!important;border-color:var(--ft-border)!important}.module-intel-summary,.module-intel-block li,.module-intel-cat li,.module-intel-priority li,.module-intel-metrics strong,.attention-center-item strong{color:var(--ft-text)!important}.module-intel-block strong,.module-intel-cat h3,.credit-score-weight-row{color:var(--ft-text-2)!important}.module-intel-note,.module-intel-copy,.module-intel-disclaimer,.module-intel-facts,.module-intel-priority span,.attention-center-disclaimer,.attention-center-empty{color:var(--ft-muted)!important}.credit-score-pill{background:var(--ft-surface-subtle)!important;border-color:var(--ft-border)!important}.btn.whatsapp{background:#eefbf3!important;border-color:#a7ddbd!important;color:#11733d!important}.btn.whatsapp:hover{background:#e1f7e9!important;border-color:#79c99a!important}

/* Mobile */
@media(max-width:1050px){.financier-nav{background:rgba(255,255,255,.97)!important;border-color:var(--ft-border)!important;box-shadow:0 10px 30px rgba(16,24,40,.14)!important}.accounts-dashboard .acc-bottom-nav{background:rgba(255,255,255,.97)!important;border-color:var(--ft-border)!important;box-shadow:0 -8px 30px rgba(16,24,40,.08)!important}}
@media(max-width:680px){.shell{padding-left:14px!important;padding-right:14px!important}.card{border-radius:14px!important}.modal-bg{align-items:flex-end!important;padding:0!important}.modal,.acc-modal{width:100%!important;max-height:92svh!important;border-radius:20px 20px 0 0!important;padding:20px!important}.metrics{grid-template-columns:repeat(2,minmax(0,1fr))!important}.metrics .card{min-height:92px!important}.table{border-radius:10px!important}.btn{min-height:44px!important}.dashboard-finance-section,.dashboard-chit-panel{padding:16px!important}}
`;
